apiVersion: v1
kind: PersistentVolume
metadata:
  name: aws-pv-sc
  labels:
    type: sc
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ebs-storage-class
  awsElasticBlockStore:
    volumeID: vol-01e02b44cccb760b4
    fsType: ext4
  volumeMode: Filesystem # Added volume mode (optional)
